pipeline {
    agent { 
        node { label 'maven' } }
    options {
        rateLimitBuilds(throttle: [count: 10000, durationName: 'day', durationCount: 1])
    stages {
        stage('Build') {
            //steps {
            //    sh 'mvn -f /root/workspace/codeby_lesson26/Hellow-Devops/pom.xml clean install'
            //}
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                //sh './jenkins/scripts/deliver.sh'
                echo "deliver ok"
            }
        }
    }
}
