pipeline {
    agent { 
        node { label 'maven' } }
    environment {
        APP_WORLD = "lesson26/Hellow-Devops"
    }
    stages {
        stage('Build') {
            steps {
                dir(env.APP_WORLD) {
                    sh 'mvn -f /root/workspace/codeby_lesson26/Hellow-Devops/pom.xml clean install'
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir(env.APP_WORLD) {
                    sh 'mvn test'
            }
            
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                //sh './jenkins/scripts/deliver.sh'
                echo "deliver ok"
            }
        }
    }
}
