pipeline {
    agent {
        docker {
            image 'maven:3.9.2'
            args '-v /root/.m2:/root/.m2'
        }
    }
    environment {
        APP_WORLD = "lesson26/Hello-World"
    }
    stages {
        stage('Build') {
            steps {
                dir(env.APP_WORLD) {
                    sh 'mvn -f pom.xml clean install'
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir(env.APP_WORLD) {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                //sh './jenkins/scripts/deliver.sh'
                echo "deliver ok"
            }
        }
    }
}
