pipeline {
    agent {
        docker {
            image 'maven:3.9.9'
            args '-v /root/.m2:/root/.m2'
        }
    } 
    environment {
        APP_DEV = "lesson26/Hello-Devops"
    }
    stages {
        stage('Build') {
            steps {
                dir(env.APP_DEV) {
                    //sh 'mvn -f pom.xml clean install'
                sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir(env.APP_DEV) {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit '**/target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                //sh './jenkins/scripts/deliver.sh'
                echo "deliver ok"
            }
        }
    }
}