name: Maven

on:
  push:
    branches: 
      - 'lesson28'
    paths:
      - 'lesson28/Hello-*/**/*.java'
jobs:
  build_world:
    if: github.repository == 'codeby-devops/lesson28/Hello-World'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build project World
      run: mvn -B package --file lesson28/Hello-World/pom.xml

  build_Jenkins:
    if: github.repository == 'codeby-devops/lesson28/Hello-Jenkins'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build project World
      run: mvn -B package --file lesson28/Hello-Jenkins/pom.xml    
  
  build_Devops:
    if: github.repository == 'codeby-devops/lesson28/Hello-Jenkins'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build project World
      run: mvn -B package --file lesson28/Hello-Devops/pom.xml       

