name: Maven

on:
  push:
    branches: [lesson28]

jobs:
  build_and_test:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build project with Maven
      run: mvn -B package --file lesson28/pom.xml
