name: Maven

on:
  push:
    branches: 
      - 'lesson28'
    # paths:
    #   - 'lesson28/Hello-*/**/*.java'
jobs:
  build_World:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Cache package app World
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('lesson28/Hello-World/pom.xml')}}
        restore-keys: ${{ runner.os }}-m2

    - name: Build project World
      run: mvn -B package --file lesson28/Hello-World/pom.xml

  build_Jenkins:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Cache package app Jenkins
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('lesson28/Hello-Jenkins/pom.xml')}}
        restore-keys: ${{ runner.os }}-m2

    - name: Build project World
      run: mvn -B package --file lesson28/Hello-Jenkins/pom.xml    
  
  build_Devops:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Cache package app Devops
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('lesson28/Hello-Devops/pom.xml')}}
        restore-keys: ${{ runner.os }}-m2

    - name: Build project World
      run: mvn -B package --file lesson28/Hello-Devops/pom.xml       

