name: Maven

on:
  push:
    branches: 
      - 'lesson28'
    # paths:
    #   - 'lesson28/Hello-*/**/*.java'
jobs:
  build_World:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Cache package app World
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml')}}
        restore-keys: ${{ runner.os }}-m2

    - name: Build project World
      run: mvn -B package --file lesson28/Hello-World/pom.xml

  build_Jenkins:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Cache package app Jenkins
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('lesson28/Hello-Jenkins/pom.xml')}}
        restore-keys: ${{ runner.os }}-m2

    - name: Build project World
      run: mvn -B package --file lesson28/Hello-Jenkins/pom.xml    
  
  build_Devops:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Cache package app Devops
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('lesson28/Hello-Devops/pom.xml')}}
        restore-keys: ${{ runner.os }}-m2

    - name: Build project World
      run: mvn -B package --file lesson28/Hello-Devops/pom.xml       

  publish-job_World:
    runs-on: ubuntu-latest
    needs: [build_World]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - run: mvn -B package --file lesson28/Hello-World/pom.xml -DskipTests
      - run: mkdir staging1 && cp target/*.jar staging1
      - uses: actions/upload-artifact@v4
        with:
          name: World-pack
          path: staging1

  publish-job_Jenkins:
    runs-on: ubuntu-latest
    needs: [build_Jenkins]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - run: mvn -B package --file lesson28/Hello-Jenkins/pom.xml -DskipTests
      - run: mkdir staging2 && cp target/*.jar staging2
      - uses: actions/upload-artifact@v4
        with:
          name: Jenkins-pack
          path: staging2

  publish-job_Devops:
    runs-on: ubuntu-latest
    needs: [build_Devops]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - run: mvn -B package --file lesson28/Hello-Devops/pom.xml -DskipTests
      - run: mkdir staging3 && cp target/*.jar staging3
      - uses: actions/upload-artifact@v4
        with:
          name: Devops-pack
          path: staging3