name: Maven

on:
  push:
    branches: [lesson28]

jobs:
  build_and_test:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build project World
      run: mvn -B package --file lesson28/Hello-World/pom.xml
    - name: Build project Jenkins
      run: mvn -B package --file lesson28/Hello-Jenkins/pom.xml
    - name: Build project Devops
      run: mvn -B package --file lesson28/Hello-Devops/pom.xml
